# Training description


# Gerenal options
log_file: log/libri.log
torch_seed: 42
numpy_seed: 42
random_seed: 42
deterministic: false

epochs: 1000
lr: 0.001
patience: 100

multi_gpu: true
num_cpu: 8

mixed_precision: true
clipping: false

# Optimizer and scheduler options
optimizer:
    type: adam
    options:

scheduler:
    type: CyclicLR
    mode: triangular2
    base_lr: 1.0e-05
    step_size_up: 3000



# Evaluation options
compute_test_eer: true
log_interval: 10
validation_frequency: 1

# Save options
tmp_model_name: model/tmp_test_libri_train_clean_360.pt
best_model_name: model/best_test_libri_train_clean_360.pt
checkpoint_frequency:
