# Training description


# Gerenal options
log_file: log/vox12.log
torch_seed: 42
numpy_seed: 42
random_seed: 42
deterministic: false

epochs: 1000
lr: 0.001
patience: 100

multi_gpu: true
num_cpu: 6

mixed_precision: true
clipping: false

# Optimizer and scheduler options
optimizer:
    type: adam
    options:

scheduler:
    type: CyclicLR
    mode: triangular2
    base_lr: 1.0e-10
    step_size_up: 40000

# Evaluation options
compute_test_eer: false
log_interval: 10
validation_frequency: 1

# Save options
tmp_model_name: model/tmp_vox12_ori.pt
best_model_name: model/best_vox12_ori.pt
checkpoint_frequency:
